#
# LuaDist Travis-CI Hook
#

# Since CMake is not directly supported we use erlang VMs
language: erlang

# Try using multiple Lua Implementations
env:
  - LUA="lua-5.1.5"     # Use automatic dependencies
  - LUA="luajit"        # Check with LuaJIT

# Allow LuaJIT based builds to fail
matrix:
  allow_failures:
    - env: LUA="luajit"
      
# We need CMake and LuaDist
install:
  - export MODULE=`basename $PWD`
  - sudo apt-get install cmake  
  - git clone git://github.com/LuaDist/bootstrap.git _luadist
  - cd _luadist
  - git submodule update --init
  - ./bootstrap
  - export LUADIST=$PWD/_install/bin/luadist
  - cd $HOME

# Use LuaDist to deploy the module
script:
  - $LUADIST _test install $LUA $MODULE-scm

# Run the test suite
after_script:
  - $LUADIST _test list # List all installed modules

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always
